### ISSUE TITLE
Some maps with non-English characters in _songSubName will fail to load

### ISSUE THREAD

**Issue by WGzeyu** [BSMGPink/PinkCore#4]
The same is the map that contains Chinese in _songSubName, [11c00](https://beatsaver.com/maps/11c00) can be load normally, but [11c03](https://beatsaver.com/maps/11c03) (and [108bd](https://beatsaver.com/maps/108bd)) prompts `Error loading data.`
It has been confirmed that there are no non-ASCII characters in the file name.
I reported the problem to SongLoader before, and darknight1050 told me that it was a PinkCore problem...
https://github.com/darknight1050/SongLoader/issues/13

**Comment by Findgoodthing** [comment]
> turns out, the font set of the game does not support those characters, so you will still see ????, but at least the maps will load with an update :)

When I disbale PinkCore the maps will load success,  Maybe is not "game does not support those characters"?

**Comment by Futuremappermydud** [comment]
> turns out, the font set of the game does not support those characters, so you will still see ????, but at least the maps will load with an update :)

Other ui shows those characters though?

**Comment by RedBrumbler** [comment]
Not the ones I tested with, it was specifically this: `ˏ₍•ɞ•₎ˎ` which didn't show up with questui and setting manually with newcsstr

**Comment by RedBrumbler** [comment]
Lmao it doesnt even work on github

**Comment by RedBrumbler** [comment]
More or less solved in v1.6.0
