### ISSUE TITLE
Requirements Shows Up On Every Map, Even If The Map Has No Requirements.

### ISSUE THREAD

**Issue by BoogieHasFun** [BSMGPink/PinkCore#6]
The requirements (eg. [?] icon) shows up on every map. ![image](https://user-images.githubusercontent.com/76754631/132075345-d7add6bb-69a6-41ce-9146-911f5c9b8f27.jpeg)![image](https://user-images.githubusercontent.com/76754631/132075348-61662c03-ceaa-456c-8bc0-fd284808fbdf.jpeg)

**Comment by RedBrumbler** [comment]
I can not reproduce this issue, is there something special about those songs ?

or is it just for everything

**Comment by BoogieHasFun** [comment]
fixed, you can close now :D
