### ISSUE TITLE
BeatSaber 1.17.1 crashes when selecting custom songs frequently

### ISSUE THREAD

**Issue by 0x4f5da2** [BSMGPink/PinkCore#7]
Possible Ways to Reproduce:
1. play a custom song
2. return to the custom song list
3. select custom songs frequently

screen recording:
https://user-images.githubusercontent.com/17794938/135766448-320dc544-fe75-4f2d-ad78-41a336f229b8.mp4

It seems that the pink core caused a segment fault, but I am not sure. 

Here is the log, hope this will help to locate the bug. The crash occurs around line 13684.
[crash.log](https://github.com/BSMGPink/PinkCore/files/7274290/crash.log)

**Comment by WGzeyu** [comment]
From the symptoms, it looks like this issues: 
https://github.com/darknight1050/SongLoader/issues/15

**Comment by 0x4f5da2** [comment]
After upgrading to PinkCore 1.6.2, the BeatSaber works fine.
